/**
 * Centralized error codes for consistent error handling across the application
 *
 * Error Code Format: {CATEGORY}_{SPECIFIC_ERROR}
 *
 * Categories:
 * - AUTH: Authentication related errors
 * - VALIDATION: Input validation errors
 * - RESOURCE: Resource access errors
 * - SERVER: Internal server errors
 * - REQUEST: Request-related errors
 */

export const ERROR_CODES = {
	// Authentication & Authorization (4xx)
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	TOKEN_INVALID: "TOKEN_INVALID",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

	// Resource Errors (4xx)
	NOT_FOUND: "NOT_FOUND",
	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",

	// Validation Errors (4xx)
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INVALID_INPUT: "INVALID_INPUT",
	MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",

	// Request Errors (4xx)
	BAD_REQUEST: "BAD_REQUEST",
	CONFLICT: "CONFLICT",
	DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
	PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
	UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
	TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
	METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",

	// Server Errors (5xx)
	INTERNAL_ERROR: "INTERNAL_ERROR",
	SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
	DATABASE_ERROR: "DATABASE_ERROR",
	EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",

	// Generic/Fallback
	HTTP_ERROR: "HTTP_ERROR",
	UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP status codes mapping
 */
export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	NO_CONTENT: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	METHOD_NOT_ALLOWED: 405,
	CONFLICT: 409,
	PAYLOAD_TOO_LARGE: 413,
	UNSUPPORTED_MEDIA_TYPE: 415,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,
	INTERNAL_SERVER_ERROR: 500,
	SERVICE_UNAVAILABLE: 503,
} as const;

export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];
